version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      DB: postgres
      PORT: 8000
      SQL_HOST: localhost
      SQL_PORT: 5432
    restart: always
    container_name: app-person-client
    build:
      context: .
      target: app-container
    volumes:
      - ./uw_person_client:/app/uw_person_client
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/postgresql/data/
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=tester
      - POSTGRES_DB=testdb
volumes:
  postgres_data:
