# Copyright 2025 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.2.11 on 2024-05-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uw_person_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthold',
            options={'ordering': ['seq']},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['-tran_term__year', '-tran_term__quarter']},
        ),
    ]
