# Copyright 2025 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.2.19 on 2025-03-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uw_person_client', '0002_alter_ordering_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudentQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'enrolled_student_queue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwnetid', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'person_queue',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='studenthold',
            options={'managed': True, 'ordering': ['seq']},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={'managed': True, 'ordering': ['-tran_term__year', '-tran_term__quarter']},
        ),
    ]
